# Generated by Django 3.0.7 on 2021-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weed',
            field=models.IntegerField(null=True),
        ),
    ]
