# Generated by Django 3.0.7 on 2021-04-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reviewerID',
        ),
    ]
