# Generated by Django 3.0.7 on 2021-04-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('asin', models.CharField(auto_created=True, max_length=2000, unique=True)),
                ('title', models.TextField(default='Title')),
                ('price', models.IntegerField(default=0)),
                ('imageUrl', models.URLField(default='URL Here', max_length=5000, null=True)),
                ('brand', models.TextField(default='Brand', null=True)),
                ('description', models.TextField(default='Description', null=True)),
                ('details', models.TextField(default='Details', null=True)),
                ('also_view', models.CharField(default='Also Viewed', max_length=900, null=True)),
                ('also_buy', models.CharField(default='Also Bought', max_length=1500, null=True)),
                ('category', models.TextField(default='Category', null=True)),
                ('main_cat', models.CharField(default='Main Cat', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField(verbose_name=range(0, 5))),
                ('reviewTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewerName', models.TextField(null=True)),
                ('reviewText', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('asin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('reviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
