# Generated by Django 3.0.7 on 2021-04-16 22:07

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210415_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Movies & TV', 'Movies & TV'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Fashion', 'Fashion'), ('Amazon Home', 'Amazon Home'), ('Health & Personal Care', 'Health & Personal Care'), ('Books', 'Books'), ('Toys & Games', 'Toys & Games'), ('Baby', 'Baby'), ('Office Products', 'Office Products'), ('All Beauty', 'All Beauty'), ('Arts, Crafts & Sewing', 'Arts, Crafts & Sewing'), ('Digital Music', 'Digital Music'), ('Home Audio & Theater', 'Home Audio & Theater'), ('Video Games', 'Video Games'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('All Electronics', 'All Electronics'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('AMAZON FASHION', 'AMAZON FASHION'), ('Camera & Photo', 'Camera & Photo'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Musical Instruments', 'Musical Instruments'), ('Automotive', 'Automotive'), ('Computers', 'Computers'), ('Grocery', 'Grocery'), ('Portable Audio & Accessories', 'Portable Audio & Accessories'), ('Software', 'Software'), ('Car Electronics', 'Car Electronics'), ('Pet Supplies', 'Pet Supplies'), ('Appliances', 'Appliances'), ('Collectible Coins', 'Collectible Coins'), ('Entertainment', 'Entertainment'), ('Luxury Beauty', 'Luxury Beauty'), ('GPS & Navigation', 'GPS & Navigation'), ('Amazon Devices', 'Amazon Devices')], default='', max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_cat',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Movies & TV', 'Movies & TV'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Fashion', 'Fashion'), ('Amazon Home', 'Amazon Home'), ('Health & Personal Care', 'Health & Personal Care'), ('Books', 'Books'), ('Toys & Games', 'Toys & Games'), ('Baby', 'Baby'), ('Office Products', 'Office Products'), ('All Beauty', 'All Beauty'), ('Arts, Crafts & Sewing', 'Arts, Crafts & Sewing'), ('Digital Music', 'Digital Music'), ('Home Audio & Theater', 'Home Audio & Theater'), ('Video Games', 'Video Games'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('All Electronics', 'All Electronics'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('AMAZON FASHION', 'AMAZON FASHION'), ('Camera & Photo', 'Camera & Photo'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Musical Instruments', 'Musical Instruments'), ('Automotive', 'Automotive'), ('Computers', 'Computers'), ('Grocery', 'Grocery'), ('Portable Audio & Accessories', 'Portable Audio & Accessories'), ('Software', 'Software'), ('Car Electronics', 'Car Electronics'), ('Pet Supplies', 'Pet Supplies'), ('Appliances', 'Appliances'), ('Collectible Coins', 'Collectible Coins'), ('Entertainment', 'Entertainment'), ('Luxury Beauty', 'Luxury Beauty'), ('GPS & Navigation', 'GPS & Navigation'), ('Amazon Devices', 'Amazon Devices')], default='', max_length=28, null=True),
        ),
    ]
